'use client'
import { useEffect } from 'react'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '../lib/utils'
const inter = Inter({ subsets: ['latin'] })
import Navbar from '../components/Navbar'
import { ThemeProvider } from './themeContext'

import { SpaceProvider } from './SpaceContext'
import Footer from '../components/Footer'

import Assistance from '../components/Assistance'
import Head from 'next/head'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth ">
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <ThemeProvider>
        <body
          className={cn(
            'min-h-screen max-w-[100vw] overflow-x-hidden font-sans antialiased scroll-smooth ',
            inter.className
          )}
        >
          <Navbar />

          <SpaceProvider>{children}</SpaceProvider>

          <Assistance />
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  )
}
